name: CI
on:
  push:
    branch:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install packages
        run: npm ci
      - name: tsc
        run: npm run tsc:check
      - name: Prettier
        run: npm run format:check
      - name: ESLint
        run: npm run lint:check
